### ISSUE TITLE
How to use it from Java?

### ISSUE THREAD

**Issue by hansgru** [myfreeweb/rxjava-http-tail#1]
Any example on how to use it from Java?
e.g. tailing a Tomcat log file from a JSP?

**Comment by myfreeweb** [comment]
Is that log file available over HTTP?  If not, this isn't the library you want.

**Comment by hansgru** [comment]
> Is that log file available over HTTP? 

No, it's not, because it would be too big and it's constantly changing, so purpose is to make it available over HTTP but only with tail.

**Comment by myfreeweb** [comment]
To make it available, you need a regular web server such as nginx.

**Comment by hansgru** [comment]
> To make it available, you need a regular web server such as nginx.

So this library can't "watch" files for changes with RX and tail those changes over HTTP, but it "tails **from** HTTP to something"?

**Comment by myfreeweb** [comment]
Exactly!

Is the description not clear enough? It says "This allows you to **follow** logs like `tail -f` **through HTTP**."
(And then the example shows reading from `http://crawl.akrasiac.org/logfile-git`)

**Comment by hansgru** [comment]
> Is the description not clear enough? 

Not sure :). The "from" was missing for me. Or maybe I was just "wish reading" :).

**Comment by davidmoten** [comment]
@hansgru this might be of interest to you: https://github.com/davidmoten/rxjava-file
