### ISSUE TITLE
Log with size based rolling

### ISSUE THREAD

**Issue by patb23** [myfreeweb/rxjava-http-tail#2]
Hi,
The logs for our app is available over http but it gets rolled over based on size. Do not know how to use offset in this case. I tested my code with 0 offset and I think it only reads the new lines (like tail, but need confirmation.) this is the behavior I want.
```groovy
lineReader = { tailResult ->
    def body = tailResult.getBody();
    def text = body.text
    println text
}

HttpTail tail = new HttpTail('http://10.90.108.43:3000/dm-access.log', 0, 200);
tail.createObservable().subscribe(lineReader)
```
Also, I got to know of this through RxJava WIKI (https://github.com/ReactiveX/RxJava/wiki) but able to run only after adding com.netflix..maven dependency. Will this work with 'io.reactivex'?
Thanks

**Comment by myfreeweb** [comment]
Hi!

I haven't touched this in a while, it was made way before they moved it to `io.reactivex`. I'm going to update that soon.

I also haven't thought about rotating logs. If you figure it out, feel free to send a pull request :) Shouldn't be hard I guess – detect that the length you get is smaller than the offset you requested, something like that.

**Comment by patb23** [comment]
Thank you. i will try your suggestion, and If could write decent code will sure publish :-). Tx for this wonderful utility.
